apiVersion: v1
kind: ConfigMap

metadata:
  name: opsboard-backend-config
  namespace: opsboard

  labels:
    app: opsboard
    component: backend

data:
  NODE_ENV: production
  PORT: "4000"
  FRONTEND_URL: http://opsboard.local