apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - database-migration-job.yaml
  - ingress.yaml

images:
  - name: opsboard-api
    newName: ghcr.io/lennhatthanh/opsboard-api
    newTag: 8c7145ad02396844eab16b408a04ea24f89e1da5

  - name: opsboard-web
    newName: ghcr.io/lennhatthanh/opsboard-web
    newTag: 8c7145ad02396844eab16b408a04ea24f89e1da5